---
title: "Schedule"
---

Schedule is tentative and subject to change 

| Date | Course | 
| --- | --- | 
| 2026-02-18 | [Introduction to geospatial data science at the World Bank](courses/data_science.qmd) | 
| 2026-03-04 | [Connectivity analytics with GOSTnets: building and using transport networks to assess access and travel time](courses/health_access.qmd) | 
| 2026-03-18 | From pixels to products: Introduction to remote sensing and earth observation from a development perspective | 
| 2026-04-01 | [Space2Stats: exploring the World Bank’s subnational geospatial aggregates using Python, DDH, and Hex API](courses/s2s_introduction.qmd) | 
| 2026-04-22 | Beyond the clouds: how to leverage all-weather, day-and-night Synthetic Aperture Radar data for WBG operations |  
| 2026-05-06 | Principles of World Bank cartography: from data to decision-ready maps | 
| 2026-05-20 | Space2Stats: People and Planet | 
| 2026-06-03 | Data collection with GEMS | 
| 2026-06-17 | Blackmarblepy: How to leverage NASA’s Black Marble nightlights products to inform development decisions | 
